#! /bin/sh

# Path to GDB macros file.  Customize for your site.
GDBMACROS=/home/idanreed/pintos/src/misc/gdb-macros
GDB=gdb
if test -f "$GDBMACROS"; then
	exec $GDB -x "$GDBMACROS" "$@" --command=/home/idanreed/pintos/src/utils/gdb-cmds 
	#--args "set architecture i386:x86-64"
else
	echo "*** $GDBMACROS does not exist ***"
	echo "*** Pintos GDB macros will not be available ***"
	exec $GDB "$@"
fi
